In [ ]:
%load_ext autoreload
%autoreload 2

In [784]:
import sys
import numpy as np
from stabilizer_states import StabilizerStates

In [785]:
np.set_printoptions(precision=3, linewidth=sys.maxsize, edgeitems=4, threshold=1024, suppress=True) 

In [712]:
def normalize(v):
    norm = np.linalg.norm(v)
    if norm == 0: 
        return v
    return v / norm

In [786]:
S1 = StabilizerStates(1)
# S1 = StabilizerStates(1, "real")
# S1 = StabilizerStates(1, "ternary")
S1.validate()

Validation for 1-qubit stabilizer dataset:
  Full count of stabilizer states (6): ✅
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ✅
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


True

In [787]:
print(S1)

[[ 1.   +0.j     0.   +0.j   ]
 [ 0.   +0.j     1.   +0.j   ]
 [ 0.707+0.j     0.707+0.j   ]
 [ 0.707+0.j    -0.707+0.j   ]
 [ 0.707+0.j     0.   +0.707j]
 [ 0.707+0.j     0.   -0.707j]]


In [789]:
S2 = StabilizerStates(2)
# S2 = StabilizerStates(2, "real")
# S2 = StabilizerStates(2, "ternary")
S2.validate()

Validation for 2-qubit stabilizer dataset:
  Full count of stabilizer states (60): ✅
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ✅
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


True

In [791]:
print(S2)

[[ 0.5  +0.j     0.5  +0.j     0.5  +0.j     0.5  +0.j   ]
 [ 0.5  +0.j    -0.5  +0.j     0.5  +0.j    -0.5  +0.j   ]
 [ 0.5  +0.j     0.5  +0.j    -0.5  +0.j    -0.5  +0.j   ]
 [ 0.5  +0.j    -0.5  +0.j    -0.5  +0.j     0.5  +0.j   ]
 [ 0.5  +0.j     0.   +0.5j    0.5  +0.j     0.   +0.5j  ]
 [ 0.5  +0.j     0.   -0.5j    0.5  +0.j     0.   -0.5j  ]
 [ 0.5  +0.j     0.   +0.5j   -0.5  +0.j     0.   -0.5j  ]
 [ 0.5  +0.j     0.   -0.5j   -0.5  +0.j     0.   +0.5j  ]
 [ 0.5  +0.j     0.5  +0.j     0.5  +0.j    -0.5  +0.j   ]
 [ 0.5  +0.j    -0.5  +0.j     0.5  +0.j     0.5  +0.j   ]
 [ 0.5  +0.j     0.5  +0.j    -0.5  +0.j     0.5  +0.j   ]
 [-0.5  +0.j     0.5  -0.j     0.5  -0.j     0.5  -0.j   ]
 [ 0.5  +0.j     0.   +0.5j    0.5  +0.j     0.   -0.5j  ]
 [ 0.5  +0.j     0.   -0.5j    0.5  +0.j     0.   +0.5j  ]
 [ 0.5  +0.j     0.   +0.5j   -0.5  +0.j     0.   +0.5j  ]
 [-0.5  +0.j     0.   +0.5j    0.5  -0.j     0.   +0.5j  ]
 [ 0.5  +0.j     0.5  +0.j     0.   +0.5j    0.   +0.5j 

In [792]:
S3 = StabilizerStates(3)
# S3 = StabilizerStates(3, "real")
# S3 = StabilizerStates(3, "ternary")
S3.validate()

Validation for 3-qubit stabilizer dataset:
  Full count of stabilizer states (1080): ✅
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ✅
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


True

In [793]:
print(S3)

[[ 0.354+0.j  0.354+0.j  0.354+0.j  0.354+0.j  0.354+0.j  0.354+0.j  0.354+0.j  0.354+0.j]
 [ 0.354+0.j -0.354+0.j  0.354+0.j -0.354+0.j  0.354+0.j -0.354+0.j  0.354+0.j -0.354+0.j]
 [ 0.354+0.j  0.354+0.j -0.354+0.j -0.354+0.j  0.354+0.j  0.354+0.j -0.354+0.j -0.354+0.j]
 [ 0.354+0.j -0.354+0.j -0.354+0.j  0.354+0.j  0.354+0.j -0.354+0.j -0.354+0.j  0.354+0.j]
 ...
 [ 0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  1.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j]
 [ 0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  1.   +0.j  0.   +0.j  0.   +0.j]
 [ 0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  1.   +0.j  0.   +0.j]
 [ 0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  1.   +0.j]]


In [779]:
S4 = StabilizerStates(4)
# S4 = StabilizerStates(4, "real")
# S4 = StabilizerStates(4, "ternary")
S4.validate()

Validation for 4-qubit stabilizer dataset:
  Full count of stabilizer states (36720): ✅
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ✅
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


True

In [794]:
print(S4)

[[ 0.25+0.j  0.25+0.j  0.25+0.j  0.25+0.j ...  0.25+0.j  0.25+0.j  0.25+0.j  0.25+0.j]
 [ 0.25+0.j -0.25+0.j  0.25+0.j -0.25+0.j ...  0.25+0.j -0.25+0.j  0.25+0.j -0.25+0.j]
 [ 0.25+0.j  0.25+0.j -0.25+0.j -0.25+0.j ...  0.25+0.j  0.25+0.j -0.25+0.j -0.25+0.j]
 [ 0.25+0.j -0.25+0.j -0.25+0.j  0.25+0.j ...  0.25+0.j -0.25+0.j -0.25+0.j  0.25+0.j]
 ...
 [ 0.  +0.j  0.  +0.j  0.  +0.j  0.  +0.j ...  1.  +0.j  0.  +0.j  0.  +0.j  0.  +0.j]
 [ 0.  +0.j  0.  +0.j  0.  +0.j  0.  +0.j ...  0.  +0.j  1.  +0.j  0.  +0.j  0.  +0.j]
 [ 0.  +0.j  0.  +0.j  0.  +0.j  0.  +0.j ...  0.  +0.j  0.  +0.j  1.  +0.j  0.  +0.j]
 [ 0.  +0.j  0.  +0.j  0.  +0.j  0.  +0.j ...  0.  +0.j  0.  +0.j  0.  +0.j  1.  +0.j]]


In [782]:
S5 = StabilizerStates(5)
# S5 = StabilizerStates(5, "real")
# S5 = StabilizerStates(5, "ternary")
S5.validate()

Validation for 5-qubit stabilizer dataset:
  Full count of stabilizer states (2423520): ✅
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ✅
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


True

In [796]:
print(S5)

[[ 0.   +0.j     0.   +0.j     0.354+0.j     0.   +0.j    ...  0.   +0.j     0.   +0.j     0.   -0.354j  0.   +0.j   ]
 [ 0.25 +0.j     0.   +0.j     0.   +0.25j   0.   +0.j    ...  0.   +0.25j   0.   +0.j    -0.25 +0.j     0.   +0.j   ]
 [ 0.25 +0.j     0.   +0.j     0.   -0.25j   0.   +0.j    ... -0.25 +0.j     0.   +0.j     0.   +0.25j   0.   +0.j   ]
 [ 0.25 +0.j    -0.25 +0.j     0.   +0.25j   0.   +0.25j  ...  0.   +0.25j   0.   +0.25j  -0.25 +0.j     0.25 +0.j   ]
 ...
 [ 0.25 +0.j    -0.25 +0.j     0.   -0.25j   0.   +0.25j  ...  0.   +0.25j   0.   -0.25j  -0.25 +0.j     0.25 +0.j   ]
 [ 0.25 +0.j    -0.25 +0.j     0.   +0.25j   0.   -0.25j  ...  0.   +0.25j   0.   +0.25j  -0.25 +0.j    -0.25 +0.j   ]
 [ 0.25 +0.j    -0.25 +0.j     0.   +0.j     0.   +0.j    ...  0.   +0.25j   0.   +0.25j   0.   +0.j     0.   +0.j   ]
 [ 0.177+0.j    -0.177+0.j     0.177+0.j    -0.177+0.j    ... -0.177+0.j    -0.177+0.j    -0.177+0.j    -0.177+0.j   ]]


In [778]:
S6 = StabilizerStates(6)
# S6 = StabilizerStates(6, "ternary")
S6.validate()

/Users/amir/dev/qc/stabilizer-states/stabilizer_states/stabilizer_states.py:50: UserWarning: The dataset loaded (S6_ternary.npy) is a partial dataset (9694080 vs. 315057600)
  warnings.warn(


Validation for 6-qubit stabilizer dataset:
  Full count of stabilizer states (315057600): ❌
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ❌
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


False

In [797]:
print(S6)

[[ 1  0  0  0 ...  0  0  0  0]
 [ 0  0  0  0 ...  0  0  0  0]
 [ 0  0  0  0 ...  0  0  0  0]
 [ 0  0  0  0 ...  0  0  0  0]
 ...
 [ 1 -1 -1 -1 ...  1 -1 -1 -1]
 [ 1 -1 -1 -1 ... -1  1  1  1]
 [ 1 -1 -1 -1 ... -1  1  1  1]
 [ 1 -1 -1 -1 ...  1 -1 -1 -1]]


We stop at 6 qubits, because the size of the 7-qubit dataset would be:

In [798]:
StabilizerStates.count(7)

81284860800

In [799]:
S7 = StabilizerStates(7)

ValueError: Missing stabilizer state dataset for 7 qubits.