In [1]:
%load_ext autoreload
%autoreload 2

In [175]:
import sys
import numpy as np
from stabilizer_states import StabilizerStates

In [645]:
np.set_printoptions(precision=3, linewidth=sys.maxsize, edgeitems=4, threshold=1024, suppress=True) 

In [712]:
def normalize(v):
    norm = np.linalg.norm(v)
    if norm == 0: 
        return v
    return v / norm

In [770]:
S1 = StabilizerStates(1)
# S1 = StabilizerStates(1, "real")
# S1 = StabilizerStates(1, "ternary")
S1.validate()

Validation for 1-qubit stabilizer dataset:
  Full count of stabilizer states (6): ✅
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ✅
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


True

In [648]:
len(S1)

6

In [649]:
print(S1)

[[ 1.   +0.j     0.   +0.j   ]
 [ 0.   +0.j     1.   +0.j   ]
 [ 0.707+0.j     0.707+0.j   ]
 [ 0.707+0.j    -0.707+0.j   ]
 [ 0.707+0.j     0.   +0.707j]
 [ 0.707+0.j     0.   -0.707j]]


In [771]:
S2 = StabilizerStates(2)
# S2 = StabilizerStates(2, "real")
# S2 = StabilizerStates(2, "ternary")
S2.validate()

Validation for 2-qubit stabilizer dataset:
  Full count of stabilizer states (60): ✅
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ✅
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


True

In [737]:
S = S2
states = S._states
support = np.count_nonzero(states, axis=1)    
amplitudes = 1 / np.sqrt(support[:, None])    
nonzero_amps_match = np.isclose(states, amplitudes)
print(np.count_nonzero(nonzero_amps_match))
# print(nonzero_amps_match[nonzero_amps_match].shape)
nonzero_amps_match = np.where(nonzero_amps_match, nonzero_amps_match, np.isclose(states, -amplitudes))
print(np.count_nonzero(nonzero_amps_match))
# np.where(np.logical_or(
#                 np.logical_or(
#                     np.logical_or(
#                         np.logical_or(np.isclose(S2._states, amplitudes), np.isclose(S2._states, -amplitudes)),
#                         np.isclose(S2._states, 1j * amplitudes),
#                     ),
#                     np.isclose(S2._states, -1j * amplitudes),
#                 ),
#                 np.isclose(S2._states, 0),
#             ) == False)
# S2[37]
# S2[39]

92
120


In [775]:
S = S4

# negative_signs = np.count_nonzero(np.sign(S._states) == -1, axis=1)
# negative_amps_power_of_two = np.all(
#     np.mod(np.log2(negative_signs, where=negative_signs > 0), 1) == 0
# )
# print(np.where(np.mod(np.log2(negative_signs, where=negative_signs > 0), 1) != 0))


# negative_signs = np.count_nonzero(np.sign(S._states) == -1, axis=1)
# positive_signs = np.count_nonzero(np.sign(S._states) == 1, axis=1)
# np.where(negative_signs[:,None] > positive_signs[:,None])
# normalize(S[19]/np.max(S[19]))
# np.where(negative_signs[:,None] > positive_signs[:,None], -1 * S._states, S._states)
# np.where(np.mod(np.log2(negative_signs, where=negative_signs > 0), 1) != 0)

# np.all(np.all(np.isclose(S._states, np.apply_along_axis(normalize, 1, S._states/np.max(S._states, axis=1)[:,None])), axis=1))
# np.where(S._states != np.apply_along_axis(normalize, 1, S._states/np.min(S._states, axis=1)[:,None]))
# print(S[37])
# print(np.apply_along_axis(normalize, 1, S._states/np.max(S._states, axis=1)[:,None])[37])
# np.save("../stabilizer_states/datasets/S4.npy", np.apply_along_axis(normalize, 1, S._states/np.max(S._states, axis=1)[:,None]))
# np.save("../stabilizer_states/datasets/S4.npy", np.where(negative_signs[:,None] > positive_signs[:,None], -1 * S._states, S._states))

In [452]:
print(S2.shape)

(60, 4)


In [602]:
print(S2)

[[ 0.5  +0.j     0.5  +0.j     0.5  +0.j     0.5  +0.j   ]
 [ 0.5  +0.j    -0.5  +0.j     0.5  +0.j    -0.5  +0.j   ]
 [ 0.5  +0.j     0.5  +0.j    -0.5  +0.j    -0.5  +0.j   ]
 [ 0.5  +0.j    -0.5  +0.j    -0.5  +0.j     0.5  +0.j   ]
 [ 0.5  +0.j     0.   +0.5j    0.5  +0.j     0.   +0.5j  ]
 [ 0.5  +0.j     0.   -0.5j    0.5  +0.j     0.   -0.5j  ]
 [ 0.5  +0.j     0.   +0.5j   -0.5  +0.j     0.   -0.5j  ]
 [ 0.5  +0.j     0.   -0.5j   -0.5  +0.j     0.   +0.5j  ]
 [ 0.5  +0.j     0.5  +0.j     0.5  +0.j    -0.5  +0.j   ]
 [ 0.5  +0.j    -0.5  +0.j     0.5  +0.j     0.5  +0.j   ]
 [ 0.5  +0.j     0.5  +0.j    -0.5  +0.j     0.5  +0.j   ]
 [-0.5  +0.j     0.5  -0.j     0.5  -0.j     0.5  -0.j   ]
 [ 0.5  +0.j     0.   +0.5j    0.5  +0.j     0.   -0.5j  ]
 [ 0.5  +0.j     0.   -0.5j    0.5  +0.j     0.   +0.5j  ]
 [ 0.5  +0.j     0.   +0.5j   -0.5  +0.j     0.   +0.5j  ]
 [-0.5  +0.j     0.   +0.5j    0.5  -0.j     0.   +0.5j  ]
 [ 0.5  +0.j     0.5  +0.j     0.   +0.5j    0.   +0.5j 

In [780]:
S3 = StabilizerStates(3)
# S3 = StabilizerStates(3, "real")
# S3 = StabilizerStates(3, "ternary")
S3.validate()

Validation for 3-qubit stabilizer dataset:
  Full count of stabilizer states (1080): ✅
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ✅
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


True

In [502]:
print(S3.shape)

(1080, 8)


In [503]:
print(S3)

[[ 0.354+0.j  0.354+0.j  0.354+0.j  0.354+0.j  0.354+0.j  0.354+0.j  0.354+0.j  0.354+0.j]
 [ 0.354+0.j -0.354+0.j  0.354+0.j -0.354+0.j  0.354+0.j -0.354+0.j  0.354+0.j -0.354+0.j]
 [ 0.354+0.j  0.354+0.j -0.354+0.j -0.354+0.j  0.354+0.j  0.354+0.j -0.354+0.j -0.354+0.j]
 [ 0.354+0.j -0.354+0.j -0.354+0.j  0.354+0.j  0.354+0.j -0.354+0.j -0.354+0.j  0.354+0.j]
 ...
 [ 0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  1.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j]
 [ 0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  1.   +0.j  0.   +0.j  0.   +0.j]
 [ 0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  1.   +0.j  0.   +0.j]
 [ 0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.   +0.j  1.   +0.j]]


In [768]:
from functools import partial

S = S4
# with np.printoptions(threshold=sys.maxsize, suppress=True):
#     print(np.unique((S3._states / np.count_nonzero(S3._states, axis=1)[:,None]), axis=0, return_counts=True)[1])
# np.all(np.real_if_close(S3._states) == (1 / np.sqrt(np.count_nonzero(S3._states, axis=1)))[:,None], axis=1)
# s = S3._states == (1 / np.count_nonzero(S3._states, axis=1))[:,None]
# np.unique(s[0], axis=0, return_counts=True)
# np.apply_along_axis(partial(np.unique, axis=0, return_counts=True), 0, s)
# unique_elems, counts = zip(*map(partial(np.unique, return_counts=True), s))
# np.vstack(unique_elems)
# S3.validate()
# print(s)
# np.real_if_close(S3._states)
# np.where(np.all(np.isreal(S3._states), axis=1) == False)
# support = (1 / np.sqrt(np.count_nonzero(S3._states, axis=1)))
# np.logical_or(np.logical_or(np.logical_or(np.logical_or(S3._states == support[:,None], S3._states == -support[:,None]), S3._states == 1j*support[:,None]), S3._states == -1j*support[:,None]), np.isclose(S3._states, 0))[521]
# np.all(np.isreal(S3._states), axis=1)
# S3[521]/S3[521][1]
# print(normalize(S3[521]/S3[521][np.nonzero(S3[521])][0]))
# (1 / np.sqrt(np.count_nonzero(S3._states, axis=1)))[521]
# print((S3._states/np.max(S3._states, axis=1)[:,None])[521])
# print(np.apply_along_axis(normalize, 1, S3._states/S3._states[np.nonzero(S3._states)][0])[521])

# np.count_nonzero(np.sign(S3._states) == -1, axis=1)
# negative_signs = np.count_nonzero(np.sign(S._states) == -1, axis=1)
# np.log2(negative_signs, where=negative_signs > 0)
# np.all(np.mod(np.log2(np.count_nonzero(np.sign(S._states) == -1, axis=1))), 1) == 0)
# np.where(np.mod(np.log2(negative_signs, where=negative_signs > 0), 1) != 0)
# np.where(~np.isclose(np.mod(np.log2(negative_signs, where=negative_signs > 0), 1), 0))
# S[19]

support = np.count_nonzero(S._states, axis=1)
num_imaginary = np.count_nonzero(np.iscomplex(S._states), axis=1)
np.where(~np.logical_or(num_imaginary == support//2, num_imaginary == 0))
# S[17939]
print(np.count_nonzero(np.iscomplex(S[17939])))
# print(np.real_if_close(S[551]))
print(np.count_nonzero(np.iscomplex(normalize(S[17939]/np.max(S[17939])))))
# S._states[551] = normalize(S[551]/S[551][1])
# num_imaginary[551]

8
4


In [779]:
S4 = StabilizerStates(4)
# S4 = StabilizerStates(4, "real")
# S4 = StabilizerStates(4, "ternary")
S4.validate()

Validation for 4-qubit stabilizer dataset:
  Full count of stabilizer states (36720): ✅
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ✅
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


True

In [143]:
print(S4.shape)

(36720, 16)


In [100]:
print(S4)

[[ 0.25+0.j  0.25+0.j  0.25+0.j ...  0.25+0.j  0.25+0.j  0.25+0.j]
 [ 0.25+0.j -0.25+0.j  0.25+0.j ... -0.25+0.j  0.25+0.j -0.25+0.j]
 [ 0.25+0.j  0.25+0.j -0.25+0.j ...  0.25+0.j -0.25+0.j -0.25+0.j]
 ...
 [ 0.  +0.j  0.  +0.j  0.  +0.j ...  1.  +0.j  0.  +0.j  0.  +0.j]
 [ 0.  +0.j  0.  +0.j  0.  +0.j ...  0.  +0.j  1.  +0.j  0.  +0.j]
 [ 0.  +0.j  0.  +0.j  0.  +0.j ...  0.  +0.j  0.  +0.j  1.  +0.j]]


In [781]:
S5 = StabilizerStates(5)
# S5 = StabilizerStates(5, "real")
# S5 = StabilizerStates(5, "ternary")
S5.validate()

Validation for 5-qubit stabilizer dataset:
  Full count of stabilizer states (2423520): ❌
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ❌
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


False

In [147]:
print(S5.shape)

(146880, 32)


In [138]:
print(S5)

[[ 0.         0.         0.25      ...  0.         0.25       0.25     ]
 [ 0.25      -0.25       0.        ...  0.25       0.         0.       ]
 [ 0.25       0.         0.25      ...  0.        -0.25       0.       ]
 ...
 [ 0.1767767 -0.1767767 -0.1767767 ... -0.1767767  0.1767767  0.1767767]
 [ 0.1767767 -0.1767767  0.1767767 ...  0.1767767 -0.1767767 -0.1767767]
 [ 0.1767767 -0.1767767 -0.1767767 ...  0.1767767 -0.1767767 -0.1767767]]


In [778]:
S6 = StabilizerStates(6)
# S6 = StabilizerStates(6, "ternary")
S6.validate()

/Users/amir/dev/qc/stabilizer-states/stabilizer_states/stabilizer_states.py:50: UserWarning: The dataset loaded (S6_ternary.npy) is a partial dataset (9694080 vs. 315057600)
  warnings.warn(


Validation for 6-qubit stabilizer dataset:
  Full count of stabilizer states (315057600): ❌
  All states unique: ✅
  Non-zero amplitude count for each state is a power of two: ✅
  Non-zero amplitude count for each state is either ±1/√|s| or ±i/√|s| (|s| is support): ❌
  Imaginary amplitude count for each state is zero or half the support: ✅
  Negative amplitude count for each state is zero or a power of two: ✅


False

In [127]:
print(S6.shape)

(9694080, 64)


In [128]:
print(S6)

[[ 1  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 1 -1 -1 ...  1  1  1]
 [ 1 -1 -1 ...  1  1  1]
 [ 1 -1 -1 ... -1 -1 -1]]


In [139]:
S7 = StabilizerStates(7)

ValueError: Missing stabilizer state dataset for 7 qubits.